language: en
streakAnnouncements: true
specialKillMessages: true
particlesEnabled: true

freeze:
  whitelistCommands:
    - msg
    - message
    - r
    - reply
  commands: # Commands to be processed when frozen player quits
    - "ban {playerName} Freeze Quit"

# hit -> combo count, combo messages, critical sound, health indicator
# death -> Disabled regions for kill streaks, special kill messages
# rank -> Earning or losing rank points
disabledRegions:
  hit:
    - spawn
  death:
    - spawn
  rank:
    - spawn

disabledWorld:
  hit: []
  death: []
  rank: []

# ipPrevent -> If victim and killer are in the same ip
# streak -> When true, attacker's kill streaks are not counted
# hit -> When true, attacker's hits are not counted
# kill -> When true, killer's kills and victim's deaths are not counted
# rank -> When true, players do not gain or lose rank points
ipPrevent:
  streak: true
  hit: true
  kill: true
  rank: true

# cooldown -> cooldown for gaining and losing points, kills, streaks etc for killing the same person repeatedly (in seconds)
cooldown: 300

rank:
  enabled: true
  defaultRank: warrior

log:
  kill:
    enable: true
    format: "[{date}] {killer} (+{+points}) ✘ {victim} (-{-points})"
  command:
    enable: true
    format: "[{date}] {sender}: '{command}' - ({beforePoints} -> {afterPoints})"

sounds:
  critical_hit_default: Experience Sound # sounds.yml
  critical_break: ENTITY_VILLAGER_NO

comboCooldown: 3

particles:
  bubble_pop:
    particle: BUBBLE_POP
    name: "Bubble Pop Effect"
    menu: true
  campfire_cosy_smoke:
    particle: CAMPFIRE_COSY_SMOKE
    name: "Campfire Cosy Smoke Effect"
    menu: true
  campfire_signal_smoke:
    particle: CAMPFIRE_SIGNAL_SMOKE
    name: "Campfire Signal Smoke Effect"
    menu: true
  cloud:
    particle: CLOUD
    name: "Cloud Effect"
    menu: true
  crimson_spore:
    particle: CRIMSON_SPORE
    name: "Crimson Spore Effect"
    menu: true
  crit:
    particle: CRIT
    name: "Crit Effect"
    menu: true
  crit_magic:
    particle: CRIT_MAGIC
    name: "Crit Magic Effect"
    menu: true
  damage_indicator:
    particle: DAMAGE_INDICATOR
    name: "Damage Indicator Effect"
    menu: true
  dragon_breath:
    particle: DRAGON_BREATH
    name: "Dragon Breath Effect"
    menu: true
  enchantment_table:
    particle: ENCHANTMENT_TABLE
    name: "Enchantment Table Effect"
    menu: true
  end_rod:
    particle: END_ROD
    name: "End Rod Effect"
    menu: true
  explosion_large:
    particle: EXPLOSION_LARGE
    name: "Explosion Large Effect"
    menu: true
  explosion_normal:
    particle: EXPLOSION_NORMAL
    name: "Explosion Normal Effect"
    menu: true
  fireworks_spark:
    particle: FIREWORKS_SPARK
    name: "Fireworks Spark Effect"
    menu: true
  flame:
    particle: FLAME
    name: "Flame Effect"
    menu: true
  heart:
    particle: HEART
    name: "Heart Effect"
    menu: true
  lava:
    particle: LAVA
    name: "Lava Effect"
    menu: true
  nautilus:
    particle: NAUTILUS
    name: "Nautilus Effect"
    menu: true
  note:
    particle: NOTE
    name: "Note Effect"
    menu: true
  portal:
    particle: PORTAL
    name: "Portal Effect"
    menu: true
  reverse_portal:
    particle: REVERSE_PORTAL
    name: "Reverse Portal Effect"
    menu: true
  slime:
    particle: SLIME
    name: "Slime Effect"
    menu: true
  smoke_normal:
    particle: SMOKE_NORMAL
    name: "Smoke Normal Effect"
    menu: true
  sneeze:
    particle: SNEEZE
    name: "Sneeze Effect"
    menu: true
  snowball:
    particle: SNOWBALL
    name: "Snowball Effect"
    menu: true
  soul:
    particle: SOUL
    name: "Soul Effect"
    menu: true
  soul_fire_flame:
    particle: SOUL_FIRE_FLAME
    name: "Soul Fire Flame Effect"
    menu: true
  spell_mob:
    particle: SPELL_MOB
    name: "Spell Mob Effect"
    menu: true
  spell_witch:
    particle: SPELL_WITCH
    name: "Spell Witch Effect"
    menu: true
  spit:
    particle: SPIT
    name: "Spit Effect"
    menu: true
  squid_ink:
    particle: SQUID_INK
    name: "Squid Ink Effect"
    menu: true
  sweep_attack:
    particle: SWEEP_ATTACK
    name: "Sweep Attack Effect"
    menu: true
  totem:
    particle: TOTEM
    name: "Totem Effect"
    menu: true
  villager_angry:
    particle: VILLAGER_ANGRY
    name: "Villager Angry Effect"
    menu: true

settingsMenu:
  title: "&6Settings"
  row: 5

  killMessages:
    slot: 20
    item: GOLDEN_SWORD
    title: "&cSpecial Kill Messages"
    lore:
      - "&7Click to the special kill message settings!"

  comboMessages:
    slot: 21
    enabled_state:
      item: GREEN_WOOL
      title: "&aCombo Messages Enabled"
      lore:
        - "&7Click to change the combo messages to &cfalse&a!"
    disabled_state:
      item: RED_WOOL
      title: "&cCombo Messages Disabled"
      lore:
        - "&7Click to change the combo messages to &atrue&c!"

  particle:
    slot: 22
    item: NETHERITE_SWORD
    title: "&bHit Effects"
    lore:
      - "&7Click to change the hit effect!"

  sound:
    slot: 23
    item: BELL
    title: "&bCombo Sound"
    lore:
      - "&7Click to change the combo sounds!"

  healthIndicator:
    slot: 24
    item: HEART_OF_THE_SEA
    title: "&bHealth Indicator"
    lore:
      - "&7Click to change the health indicator settings!"

  filler:
    enable: true
    items:
      pink:
        item: PINK_STAINED_GLASS_PANE
        title: " " # Use blank for nothing
        lore:
          - "&7www.softepen.com"
        slots:
          - 9
          - 18
          - 27
          - 17
          - 26
          - 35
      lime:
        item: LIME_STAINED_GLASS_PANE
        title: " " # Use blank for nothing
        lore:
          - "&7www.softepen.com"
        slots:
          - 11
          - 13
          - 15
          - 29
          - 31
          - 33
      red:
        item: RED_STAINED_GLASS_PANE
        title: " " # Use blank for nothing
        lore:
          - "&7www.softepen.com"
        slots:
          - 12
          - 14
          - 30
          - 32

killMessagesMenu:
  title: "&cSpecial Kill Messages"
  row: 3

  selected:
    item: YELLOW_STAINED_GLASS_PANE
    title: "&e{message}"
    lore:
      - "&aClick to remove the message"

  hasPerm:
    item: GREEN_STAINED_GLASS_PANE
    title: "&a{message}"
    lore:
      - "&7Click to select the message"

  hasNotPerm:
    item: RED_STAINED_GLASS_PANE
    title: "&c{message}"
    lore:
      - "&7Visit &bwww.softepen.com &7to buy the message"

  back:
    slot: 22
    item: BARRIER
    title: "&cBack"
    lore: []

  filler:
    enable: true
    items:
      gray:
        item: GRAY_STAINED_GLASS_PANE
        title: " " # Use blank for nothing
        lore:
          - "&7www.softepen.com"
        slots:
          - 18
          - 19
          - 20
          - 21
          - 23
          - 24
          - 25
          - 26

colorSelectMenu:
  title: "&6Color Select"
  row: 3
  item: WOOL # must be WOOL, CONCRETE, CONCRETE_POWDER, STAINED_GLASS, STAINED_GLASS_PANE or DYE

  selected:
    lore:
      - "&aSelected color"

  unselected:
    lore:
      - "&aClick to select the color"

  indicator:
    slot: 21
    enabled_state:
      item: GREEN_WOOL
      title: "&aHealth Indicator Enabled"
      lore:
        - "&7Click to change the health indicator to &cfalse&a!"
    disabled_state:
      item: RED_WOOL
      title: "&cHealth Indicator Disabled"
      lore:
        - "&7Click to change the health indicator to &atrue&c!"

  back:
    slot: 23
    item: BARRIER
    title: "&cBack"
    lore: []

  filler:
    enable: true
    items:
      gray:
        item: GRAY_STAINED_GLASS_PANE
        title: " " # Use blank for nothing
        lore:
          - "&7www.softepen.com"
        slots:
          - 18
          - 19
          - 20
          - 22
          - 24
          - 25
          - 26

soundSelectMenu:
  title: "&6Sound Select"
  row: 3

  selected:
    item: GREEN_STAINED_GLASS_PANE
    lore:
      - "&aSelected sound"

  unselected:
    item: RED_STAINED_GLASS_PANE
    lore:
      - "&aClick to select the sound"

  sound:
    slot: 21
    enabled_state:
      item: GREEN_WOOL
      title: "&aSound Enabled"
      lore:
        - "&7Click to change the sound to &cfalse&a!"
    disabled_state:
      item: RED_WOOL
      title: "&cSound Disabled"
      lore:
        - "&7Click to change the sound to &atrue&c!"

  back:
    slot: 23
    item: BARRIER
    title: "&cBack"
    lore: []

  filler:
    enable: true
    items:
      gray:
        item: GRAY_STAINED_GLASS_PANE
        title: " " # Use blank for nothing
        lore:
          - "&7www.softepen.com"
        slots:
          - 18
          - 19
          - 20
          - 22
          - 24
          - 25
          - 26

particleSelectMenu:
  title: "&cHit Effects"
  row: 3

  selected:
    item: YELLOW_STAINED_GLASS_PANE
    title: "&e{name}"
    lore:
      - "&aClick to remove the effect"

  hasPerm:
    item: GREEN_STAINED_GLASS_PANE
    title: "&a{name}"
    lore:
      - "&7Click to select the effect"

  hasNotPerm:
    item: RED_STAINED_GLASS_PANE
    title: "&c{name}"
    lore:
      - "&7Visit &bwww.softepen.com &7to buy the effect"

  back:
    slot: 22
    item: BARRIER
    title: "&cBack"
    lore: []

  filler:
    enable: true
    items:
      gray:
        item: GRAY_STAINED_GLASS_PANE
        title: " " # Use blank for nothing
        lore:
          - "&7www.softepen.com"
        slots:
          - 18
          - 19
          - 20
          - 21
          - 23
          - 24
          - 25
          - 26

profileMenu:
  title: "&6{player} Profile"
  row: 3

  profile:
    slot: 10
    lore:
      - "&aKills: &e{kills}"
      - "&aDeaths: &e{deaths}"
      - "&aK/D: &e{kd}"
      - "&aLast Combo: &e{lastCombo}"
      - "&aCombo Record: &e{comboRecord}"
      - "&aKill Series: &e{killSeries}"
      - "&aKill Series Record: &e{killSeriesRecord}"

  last5deaths:
    slot: 12
    item: FIRE_CORAL
    title: "&cLast 5 Deaths"
    lore:
      - "&7#1 &6- &a{1} &7(&b{time1}&7)"
      - "&7#2 &6- &a{2} &7(&b{time2}&7)"
      - "&7#3 &6- &a{3} &7(&b{time3}&7)"
      - "&7#4 &6- &a{4} &7(&b{time4}&7)"
      - "&7#5 &6- &a{5} &7(&b{time5}&7)"
  last5kills:
    slot: 13
    item: HORN_CORAL
    title: "&aLast 5 Kills"
    lore:
      - "&7#1 &6- &a{1} &7(&b{time1}&7)"
      - "&7#2 &6- &a{2} &7(&b{time2}&7)"
      - "&7#3 &6- &a{3} &7(&b{time3}&7)"
      - "&7#4 &6- &a{4} &7(&b{time4}&7)"
      - "&7#5 &6- &a{5} &7(&b{time5}&7)"

  top5deaths:
    slot: 14
    item: TUBE_CORAL
    title: "&cTop 5 Deaths"
    lore:
      - "&7#1 &6- &c{1} &6- &b{count1}"
      - "&7#2 &6- &c{2} &6- &b{count2}"
      - "&7#3 &6- &c{3} &6- &b{count3}"
      - "&7#4 &6- &c{4} &6- &b{count4}"
      - "&7#5 &6- &c{5} &6- &b{count5}"
  top5kills:
    slot: 15
    item: BRAIN_CORAL
    title: "&aTop 5 Kills"
    lore:
      - "&7#1 &6- &a{1} &6- &b{count1}"
      - "&7#2 &6- &a{2} &6- &b{count2}"
      - "&7#3 &6- &a{3} &6- &b{count3}"
      - "&7#4 &6- &a{4} &6- &b{count4}"
      - "&7#5 &6- &a{5} &6- &b{count5}"

  killDeathInfo:
    slot: 16
    item: SKELETON_SKULL
    title: "&bKill/Death Info"
    lore:
      - "&7You killed &b{player} &a{kill} &7times."
      - "&7You killed by &b{player} &c{death} &7times."

  filler:
    enable: false
    items: []