license: yourLicenseCode

language: en
streakAnnouncements: true
specialKillMessages: true

freeze:
  commands: # Commands to be processed when frozen player quits
    - "ban {playerName} Freeze Quit"

sounds:
  critical_hit_default: Experience Sound # sounds.yml
  critical_break: ENTITY_VILLAGER_NO

comboCooldown: 3

settingsMenu:
  title: "&6Settings"
  row: 6

  profile:
    slot: 13
    lore:
      - "&aKills: &e{kills}"
      - "&aDeaths: &e{deaths}"
      - "&aLast Combo: &e{lastCombo}"
      - "&aCombo Record: &e{comboRecord}"
      - "&aKill Series: &e{killSeries}"
      - "&aKill Series Record: &e{killSeriesRecord}"

  killMessages:
    slot: 20
    item: GOLDEN_SWORD
    title: "&cSpecial Kill Messages"
    lore:
      - "&7Click to the special kill message settings!"

  comboMessages:
    slot: 21
    enabled_state:
      item: GREEN_WOOL
      title: "&aCombo Messages Enabled"
      lore:
        - "&7Click to change the combo messages to &cfalse&a!"
    disabled_state:
      item: RED_WOOL
      title: "&cCombo Messages Disabled"
      lore:
        - "&7Click to change the combo messages to &atrue&c!"

  sound:
    slot: 22
    item: BELL
    title: "&bCombo Sound"
    lore:
      - "&7Click to change the combo sounds!"

  enable:
    slot: 23
    enabled_state:
      item: GREEN_WOOL
      title: "&aHealth Indicator Enabled"
      lore:
        - "&7Click to change the health indicator to &cfalse&a!"
    disabled_state:
      item: RED_WOOL
      title: "&cHealth Indicator Disabled"
      lore:
        - "&7Click to change the health indicator to &atrue&c!"

  color:
    slot: 24
    item: WOOL # must be WOOL, CONCRETE, CONCRETE_POWDER, STAINED_GLASS, STAINED_GLASS_PANE or DYE
    title: "&bHealth Color"
    lore:
      - "&7Click to change the health indicator color!"

  filler:
    enable: true
    items:
      pink:
        item: PINK_STAINED_GLASS_PANE
        title: " " # Use blank for nothing
        lore:
          - "&7www.softepen.com"
        slots:
          - 9
          - 17
          - 18
          - 26
          - 27
          - 35
          - 36
          - 44
      lime:
        item: LIME_STAINED_GLASS_PANE
        title: " " # Use blank for nothing
        lore:
          - "&7www.softepen.com"
        slots:
          - 29
          - 31
          - 33
      red:
        item: RED_STAINED_GLASS_PANE
        title: " " # Use blank for nothing
        lore:
          - "&7www.softepen.com"
        slots:
          - 30
          - 32

killMessagesMenu:
  title: "&cSpecial Kill Messages"
  row: 3

  selected:
    item: YELLOW_STAINED_GLASS_PANE
    title: "&e{message}"
    lore:
      - "&aClick to remove the message"

  hasPerm:
    item: GREEN_STAINED_GLASS_PANE
    title: "&a{message}"
    lore:
      - "&7Click to select the message"

  hasNotPerm:
    item: RED_STAINED_GLASS_PANE
    title: "&c{message}"
    lore:
      - "&7Visit &bwww.softepen.com &7to buy the message"

  back:
    slot: 22
    item: BARRIER
    title: "&cBack"
    lore: []

  filler:
    enable: true
    items:
      lime:
        item: LIME_STAINED_GLASS_PANE
        title: " " # Use blank for nothing
        lore:
          - "&7www.softepen.com"
        slots:
          - 18
          - 19
          - 20
          - 21
          - 23
          - 24
          - 25
          - 26

colorSelectMenu:
  title: "&6Color Select"
  row: 3

  selected:
    lore:
      - "&aSelected color"

  unselected:
    lore:
      - "&aClick to select the color"

  back:
    slot: 22
    item: BARRIER
    title: "&cBack"
    lore: []

  filler:
    enable: true
    items:
      lime:
        item: LIME_STAINED_GLASS_PANE
        title: " " # Use blank for nothing
        lore:
          - "&7www.softepen.com"
        slots:
          - 18
          - 19
          - 20
          - 21
          - 23
          - 24
          - 25
          - 26

soundSelectMenu:
  title: "&6Sound Select"
  row: 3

  selected:
    item: GREEN_STAINED_GLASS_PANE
    lore:
      - "&aSelected sound"

  unselected:
    item: RED_STAINED_GLASS_PANE
    lore:
      - "&aClick to select the sound"

  sound:
    slot: 21
    enabled_state:
      item: GREEN_WOOL
      title: "&aSound Enabled"
      lore:
        - "&7Click to change the sound to &cfalse&a!"
    disabled_state:
      item: RED_WOOL
      title: "&cSound Disabled"
      lore:
        - "&7Click to change the sound to &atrue&c!"

  back:
    slot: 23
    item: BARRIER
    title: "&cBack"
    lore: []

  filler:
    enable: true
    items:
      lime:
        item: LIME_STAINED_GLASS_PANE
        title: " " # Use blank for nothing
        lore:
          - "&7www.softepen.com"
        slots:
          - 18
          - 19
          - 20
          - 22
          - 24
          - 25
          - 26

profileMenu:
  title: "&6{player} Profile"
  row: 6

  deaths:
    slot: 20
    item: SKELETON_SKULL
    title: "&cTotal Deaths"
    lore:
      - "&7{player} &cdied {deaths} &7times"
  kills:
    slot: 29
    item: WITHER_SKELETON_SKULL
    title: "&aTotal Kills"
    lore:
      - "&7{player} &ahas {kills} &7kills"

  last5deaths:
    slot: 21
    item: SKELETON_SKULL
    title: "&cLast 5 Deaths"
    lore:
      - "&7#1 &6- &a{1} &7(&b{time1}&7)"
      - "&7#2 &6- &a{2} &7(&b{time2}&7)"
      - "&7#3 &6- &a{3} &7(&b{time3}&7)"
      - "&7#4 &6- &a{4} &7(&b{time4}&7)"
      - "&7#5 &6- &a{5} &7(&b{time5}&7)"
  last5kills:
    slot: 30
    item: WITHER_SKELETON_SKULL
    title: "&aLast 5 Kills"
    lore:
      - "&7#1 &6- &a{1} &7(&b{time1}&7)"
      - "&7#2 &6- &a{2} &7(&b{time2}&7)"
      - "&7#3 &6- &a{3} &7(&b{time3}&7)"
      - "&7#4 &6- &a{4} &7(&b{time4}&7)"
      - "&7#5 &6- &a{5} &7(&b{time5}&7)"

  top5deaths:
    slot: 22
    item: SKELETON_SKULL
    title: "&cTop 5 Deaths"
    lore:
      - "&7#1 &6- &c{1} &6- &b{count1}"
      - "&7#2 &6- &c{2} &6- &b{count2}"
      - "&7#3 &6- &c{3} &6- &b{count3}"
      - "&7#4 &6- &c{4} &6- &b{count4}"
      - "&7#5 &6- &c{5} &6- &b{count5}"
  top5kills:
    slot: 31
    item: WITHER_SKELETON_SKULL
    title: "&aTop 5 Kills"
    lore:
      - "&7#1 &6- &a{1} &6- &b{count1}"
      - "&7#2 &6- &a{2} &6- &b{count2}"
      - "&7#3 &6- &a{3} &6- &b{count3}"
      - "&7#4 &6- &a{4} &6- &b{count4}"
      - "&7#5 &6- &a{5} &6- &b{count5}"

  lastCombo:
    slot: 23
    item: SKELETON_SKULL
    title: "&aLast Combo"
    lore:
      - "&7{player}'s last combo &a{lastCombo}"
  comboRecord:
    slot: 32
    item: WITHER_SKELETON_SKULL
    title: "&bCombo Record"
    lore:
      - "&7{player}'s combo record &a{comboRecord}"

  currentStreak:
    slot: 24
    item: SKELETON_SKULL
    title: "&aCurrent Streak"
    lore:
      - "&7{player}'s current streak &a{currentStreak}"
  streakRecord:
    slot: 33
    item: WITHER_SKELETON_SKULL
    title: "&bStreak Record"
    lore:
      - "&7{player}'s streak record &a{streakRecord}"

  back:
    slot: 49
    item: BARRIER
    title: "&cBack"
    lore: []

  filler:
    enable: false
    items: []