license: yourLicenseCode

language: en
streakAnnouncements: true
specialKillMessages: true

sounds:
  critical_hit: default # sounds.yml
  critical_break: ENTITY_VILLAGER_NO

comboCooldown: 3

settingsMenu:
  title: "&6Settings"
  row: 6

  profile:
    slot: 13
    lore:
      - "&aKills: &e{kills}"
      - "&aDeaths: &e{deaths}"
      - "&aLast Combo: &e{lastCombo}"
      - "&aCombo Record: &e{comboRecord}"
      - "&aKill Series: &e{killSeries}"
      - "&aKill Series Record: &e{killSeriesRecord}"

  killMessages:
    slot: 21
    item: SKELETON_SKULL
    title: "&cSpecial Kill Messages"
    lore:
      - "&7Click to the special kill message settings!"

  comboMessages:
    slot: 23
    enabled_state:
      item: GREEN_WOOL
      title: "&aCombo Messages Enabled"
      lore:
        - "&7Click to change the combo messages to &cfalse&a!"
    disabled_state:
      item: RED_WOOL
      title: "&cCombo Messages Disabled"
      lore:
        - "&7Click to change the combo messages to &atrue&c!"

  sound:
    slot: 31
    enabled_state:
      item: BELL
      title: "&aSound Enabled"
      lore:
        - "&7Click to change the sound to &cfalse&a!"
    disabled_state:
      item: BELL
      title: "&cSound Disabled"
      lore:
        - "&7Click to change the sound to &atrue&c!"

  enable:
    slot: 39
    enabled_state:
      item: GREEN_WOOL
      title: "&aHealth Indicator Enabled"
      lore:
        - "&7Click to change the health indicator to &cfalse&a!"
    disabled_state:
      item: RED_WOOL
      title: "&cHealth Indicator Disabled"
      lore:
        - "&7Click to change the health indicator to &atrue&c!"

  color:
    slot: 41
    item: WOOL # must be WOOL, CONCRETE, CONCRETE_POWDER, STAINED_GLASS, STAINED_GLASS_PANE or DYE
    title: "&bHealth Color"
    lore:
      - "&7Click to change the health indicator color!"

  filler:
    enable: false
    item: ORANGE_STAINED_GLASS_PANE
    title: " " # Use blank for nothing
    lore:
      - "&7www.softepen.com"

killMessagesMenu:
  title: "&cSpecial Kill Messages"
  row: 3

  selected:
    item: YELLOW_STAINED_GLASS_PANE
    title: "&e{message}"
    lore:
      - "&aClick to remove the message"

  hasPerm:
    item: GREEN_STAINED_GLASS_PANE
    title: "&a{message}"
    lore:
      - "&7Click to select the message"

  hasNotPerm:
    item: RED_STAINED_GLASS_PANE
    title: "&c{message}"
    lore:
      - "&7Visit &bwww.softepen.com &7to buy the message"

  back:
    slot: 22
    item: BARRIER
    title: "&cBack"
    lore: []

  filler:
    enable: false
    item: ORANGE_STAINED_GLASS_PANE
    title: " " # Use blank for nothing
    lore:
      - "&7www.softepen.com"

colorSelectMenu:
  title: "&6Color Select"
  row: 3

  selected:
    lore:
      - "&aSelected color"

  unselected:
    lore:
      - "&aClick to select the color"

  back:
    slot: 22
    item: BARRIER
    title: "&cBack"
    lore: []

  filler:
    enable: false
    item: ORANGE_STAINED_GLASS_PANE
    title: " " # Use blank for nothing
    lore:
      - "&7www.softepen.com"